### ISSUE TITLE
Running Zip-NeRF + CamP on TPUs

### ISSUE THREAD

**Issue by Piflyer** [jonbarron/camp_zipnerf#16]
Hi there,
What are the configurations that need to be changed to get Zip-NeRF and CamP to work on the TPUs? I tried to use the default `configs/zipnerf/360.gin` to train the Mip-NeRF 360 datasets with, but I get the following error and can't quite figure out how to disable the hash encoding. In that case, would it be better if I ran Mip-NeRF 360 on the TPUs instead? Thanks!

```
Traceback (most recent call last):
  File "/home/tnguyen1/camp_zipnerf/train.py", line 557, in <module>
    app.run(main)
  File "/home/tnguyen1/.local/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/tnguyen1/.local/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/tnguyen1/camp_zipnerf/train.py", line 142, in main
    model, state, render_eval_pfn, train_pstep, lr_fn = train_utils.setup_model(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tnguyen1/camp_zipnerf/internal/train_utils.py", line 828, in setup_model
    model, variables = models.construct_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tnguyen1/camp_zipnerf/internal/models.py", line 444, in construct_model
    init_variables = model.init(
                     ^^^^^^^^^^^
  File "/home/tnguyen1/camp_zipnerf/internal/models.py", line 279, in __call__
    ray_results = mlp(
                  ^^^^
  File "/home/tnguyen1/camp_zipnerf/internal/models.py", line 779, in __call__
    raw_density, x = predict_density(means, covs, **predict_density_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tnguyen1/camp_zipnerf/internal/models.py", line 680, in predict_density
    raise ValueError('Hash Encodings should not be used on a TPU.')
ValueError: Hash Encodings should not be used on a TPU.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.```

**Comment by jonbarron** [comment]
Yeah it's just not possible to run Zip-NeRF on a TPU. You could replace the NGP grid with an MLP and it should work, it'll just be 10x slower. You're probably better off using the mip-NeRF 360 codebase though.

**Comment by Piflyer** [comment]
Sounds good, thanks!
